services:
  - type: web
    name: beam-analysis
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python app.py
    region: oregon
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
